"""Local Docker pgvector helper tests that do not require Docker."""

from __future__ import annotations

import sys
from pathlib import Path

from scripts import dev_pgvector
from scripts.dev_pgvector import PgvectorConfig, write_env_file


def test_pgvector_config_builds_backend_urls_with_escaped_credentials() -> None:
    config = PgvectorConfig(
        user="my user",
        password="pa:ss/word",
        database="my db",
        host="127.0.0.1",
        port=55432,
    )

    assert (
        config.database_url
        == "postgresql+psycopg://my%20user:pa%3Ass%2Fword@127.0.0.1:55432/my%20db"
    )
    assert (
        config.masked_database_url == "postgresql+psycopg://my%20user:***@127.0.0.1:55432/my%20db"
    )


def test_write_env_file_uses_local_pgvector_database_url(tmp_path: Path) -> None:
    env_file = tmp_path / ".env.pgvector.local"
    config = PgvectorConfig(env_file=env_file)

    write_env_file(config)

    content = env_file.read_text(encoding="utf-8")
    assert "MY_AGENTS_DATABASE_URL=postgresql+psycopg://" in content
    assert "MY_AGENTS_TEST_DATABASE_URL=postgresql+psycopg://" in content
    assert "MY_AGENTS_AUTO_CREATE_TABLES=false" in content
    assert "MY_AGENTS_SESSION_COOKIE_SECURE=false" in content
    assert "MY_AGENTS_AUTH_EMAIL_MODE=local" in content
    assert "MY_AGENTS_AUTH_DEV_OUTBOX_ENABLED=true" in content
    assert "MY_AGENTS_CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000" in content
    assert "Generated by: uv run python -m scripts.dev_pgvector env" in content


def test_run_migrations_reuses_current_python_interpreter(monkeypatch) -> None:
    captured: dict[str, object] = {}

    def capture_run(command, *, env=None, check=True):  # noqa: ANN001, ANN202
        captured.update(command=command, env=env, check=check)

    monkeypatch.setattr(dev_pgvector, "run", capture_run)

    dev_pgvector.run_migrations(PgvectorConfig())

    assert captured["command"] == [sys.executable, "-m", "alembic", "upgrade", "head"]
    assert captured["env"]["MY_AGENTS_AUTO_CREATE_TABLES"] == "false"


def test_migration_smoke_reuses_current_python_interpreter(monkeypatch) -> None:
    captured: dict[str, object] = {}

    def capture_run(command, *, env=None, check=True):  # noqa: ANN001, ANN202
        captured.update(command=command, env=env, check=check)

    monkeypatch.setattr(dev_pgvector, "run", capture_run)

    dev_pgvector.run_external_migration_smoke(PgvectorConfig())

    assert captured["command"] == [
        sys.executable,
        "-m",
        "pytest",
        "tests/test_migrations.py",
        "-q",
    ]
    assert captured["env"]["MY_AGENTS_AUTO_CREATE_TABLES"] == "false"
