"""Protocol-neutral contracts for agent-requested user interactions."""

from my_agents.interactions.schemas import (
    DOCUMENT_SELECTION_REFINEMENT_MAX_ATTEMPTS,
    DOCUMENT_SELECTION_REFINEMENT_MAX_LENGTH,
    DOCUMENT_SELECTION_SHORTLIST_LIMIT,
    INTERACTION_SCHEMA_VERSION,
    LEGACY_INTERACTION_SCHEMA_VERSION,
    ConversationRunRefineRequestV2,
    ConversationRunResumeRequest,
    ConversationRunResumeRequestType,
    ConversationRunSelectRequestV2,
    DocumentSelectionOption,
    DocumentSelectionOptionsResponse,
    DocumentSelectionOptionsResponseV2,
    DocumentSelectionOptionsResult,
    DocumentSelectionOptionV2,
    InteractionReference,
    InteractionReferenceV2,
    InteractionSchemaVersion,
    InteractionType,
    PendingDocumentSelection,
    PendingDocumentSelectionV2,
    PendingInteraction,
    conversation_run_resume_request_adapter,
    pending_interaction_adapter,
)

__all__ = [
    "DOCUMENT_SELECTION_REFINEMENT_MAX_ATTEMPTS",
    "DOCUMENT_SELECTION_REFINEMENT_MAX_LENGTH",
    "DOCUMENT_SELECTION_SHORTLIST_LIMIT",
    "INTERACTION_SCHEMA_VERSION",
    "LEGACY_INTERACTION_SCHEMA_VERSION",
    "ConversationRunRefineRequestV2",
    "ConversationRunResumeRequest",
    "ConversationRunResumeRequestType",
    "ConversationRunSelectRequestV2",
    "DocumentSelectionOption",
    "DocumentSelectionOptionV2",
    "DocumentSelectionOptionsResult",
    "DocumentSelectionOptionsResponse",
    "DocumentSelectionOptionsResponseV2",
    "InteractionReference",
    "InteractionReferenceV2",
    "InteractionSchemaVersion",
    "InteractionType",
    "PendingDocumentSelection",
    "PendingDocumentSelectionV2",
    "PendingInteraction",
    "conversation_run_resume_request_adapter",
    "pending_interaction_adapter",
]
