from typing import Annotated, TypedDict

from dotenv import load_dotenv
from langchain.messages import AnyMessage, HumanMessage, SystemMessage
from langchain_core.runnables import RunnableConfig
from langchain_openai import ChatOpenAI
from langgraph.checkpoint.memory import InMemorySaver
from langgraph.graph import END, START, StateGraph, add_messages
from pydantic import BaseModel, Field

from my_agents.settings import get_settings

load_dotenv()

settings = get_settings()
llm = ChatOpenAI(model=settings.openai_model, reasoning_effort="low")


class Plan(BaseModel):
    topic: str = Field(description="Topic for user query")
    learning_goal: str = Field(description="Objective of learning")
    steps: list[str] = Field(
        default_factory=list,
        description="List of explanations to reach the learning goal",
    )


class DraftReview(BaseModel):
    approved: bool = Field(False, description="Whether draft satisfies steps provided by planner")
    reason: str = Field("", description="Reason for approval or rejection")
    revision_instruction: str = Field("", description="How executor should revise its draft")


class StudyCoachState(TypedDict, total=False):
    messages: Annotated[list[AnyMessage], add_messages]
    topic: str
    plan: Plan
    draft_answer: str
    critic_decision: DraftReview
    revision_count: int


def planner(state: StudyCoachState):
    print("\n[planner] creating learning plan")
    system_prompt = """
    You are a planner of a study coach group.
    Generate a plan based on user's query.
    """
    plan = llm.with_structured_output(Plan).invoke(
        [
            SystemMessage(content=system_prompt),
            HumanMessage(content=state["messages"][-1].content),
        ]
    )

    print(f"[planner] topic: {plan.topic}")
    print(f"[planner] learning_goal: {plan.learning_goal}")
    print(f"[planner] steps: {plan.steps}")

    return {"plan": plan}


def executor(state: StudyCoachState):
    print("\n[executor] writing draft answer")
    last_message = state["messages"][-1]
    plan = state["plan"]
    revision_count = state.get("revision_count", 0)
    review = state.get("critic_decision")
    if not last_message or not plan:
        return {}

    evaluation = "None"
    if review:
        evaluation = f"reason: {review.reason}. revision_instruction: {review.revision_instruction}"

    system_prompt = f"""
    You are an executor of a study coach group.
    A planner has planned out user's learning path.
    Generate draft response based on planner's plan.
    You may be given with critic's decision if your previous draft
    did not pass its evaluation.

    PLAN:
    topic: {plan.topic}
    learning_goal: {plan.learning_goal}
    steps: {plan.steps}

    Evaluation:
    {evaluation}
    """

    draft = llm.invoke([SystemMessage(content=system_prompt)])
    next_revision_count = revision_count + (1 if review else 0)

    print(f"[executor] revision_count: {next_revision_count}")
    print(f"[executor] draft preview: {draft.content[:160]}...")
    return {
        "draft_answer": draft.content,
        "revision_count": next_revision_count,
    }


def critic(state: StudyCoachState):
    print("\n[critic] reviewing draft answer")
    last_message = state["messages"][-1]
    plan = state["plan"]
    draft = state["draft_answer"]
    if not last_message or not plan or not draft:
        return {}

    system_prompt = f"""
    You are a reviewer of a draft generated by executor of study coach group.

    Review the draft whether it satisfies learning steps provided by planner.

    PLAN:
    topic: {plan.topic}
    learning_goal: {plan.learning_goal}
    steps: {plan.steps}

    DRAFT:
    {draft}
    """

    verdict = llm.with_structured_output(DraftReview).invoke([SystemMessage(content=system_prompt)])

    print(f"[critic] approved: {verdict.approved}")
    print(f"[critic] reason: {verdict.reason}")
    if verdict.revision_instruction:
        print(f"[critic] revision_instruction: {verdict.revision_instruction}")

    return {"critic_decision": verdict}


graph = StateGraph(StudyCoachState)
graph.add_node("planner", planner)
graph.add_node("executor", executor)
graph.add_node("critic", critic)

graph.add_edge(START, "planner")


def route(state: StudyCoachState):
    verdict = state.get("critic_decision")
    revision_count = state.get("revision_count", 0)

    print("\n[route] deciding next node")
    print(f"[route] revision_count: {revision_count}")

    if not verdict:
        print("[route] no critic verdict; ending")
        return "END"
    if verdict.approved:
        print("[route] critic approved; ending")
        return "END"
    if revision_count >= 2:
        print("[route] max revisions reached; ending")
        return "END"

    print("[route] critic rejected; going back to executor")
    return "executor"


graph.add_edge("planner", "executor")
graph.add_edge("executor", "critic")
graph.add_conditional_edges("critic", route, {"executor": "executor", "END": END})
config: RunnableConfig = {"configurable": {"thread_id": "1"}}
group = graph.compile(checkpointer=InMemorySaver())

if __name__ == "__main__":
    while True:
        try:
            user_input = input("🧑‍💻 User: ")
            if user_input.lower() in ["/quit", "/exit", "/q"]:
                print("Goodbye!")
                break

            result = group.invoke(
                {"messages": [HumanMessage(content=user_input)]},
                config=config,
            )

            print("\n[final answer]")
            print(result.get("draft_answer", "No draft answer was created."))

        except KeyboardInterrupt:
            print("\nGoodbye!")
            break
        except Exception as exc:
            print(f"{type(exc).__name__}: {exc}")
            break
