"""Local Docker pgvector helper for backend development.

This script intentionally manages only a disposable local Docker container. It does
not contact hosted providers, store real secrets, or deploy anything.
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
import time
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import quote

DEFAULT_IMAGE = "pgvector/pgvector:pg17"
DEFAULT_CONTAINER = "my-agents-pgvector"
DEFAULT_VOLUME = "my_agents_pgvector_data"
DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 5433
DEFAULT_USER = "my_agents"
DEFAULT_PASSWORD = "my_agents_dev_password"
DEFAULT_DATABASE = "my_agents"
DEFAULT_ENV_FILE = ".env.pgvector.local"


@dataclass(frozen=True)
class PgvectorConfig:
    """Local pgvector container and backend env wiring."""

    image: str = DEFAULT_IMAGE
    container: str = DEFAULT_CONTAINER
    volume: str = DEFAULT_VOLUME
    host: str = DEFAULT_HOST
    port: int = DEFAULT_PORT
    user: str = DEFAULT_USER
    password: str = DEFAULT_PASSWORD
    database: str = DEFAULT_DATABASE
    env_file: Path = Path(DEFAULT_ENV_FILE)
    pull: bool = True

    @property
    def database_url(self) -> str:
        user = quote(self.user, safe="")
        password = quote(self.password, safe="")
        database = quote(self.database, safe="")
        return f"postgresql+psycopg://{user}:{password}@{self.host}:{self.port}/{database}"

    @property
    def masked_database_url(self) -> str:
        user = quote(self.user, safe="")
        database = quote(self.database, safe="")
        return f"postgresql+psycopg://{user}:***@{self.host}:{self.port}/{database}"


class CommandError(RuntimeError):
    """Raised when a local Docker or Python command fails."""


def main(argv: Sequence[str] | None = None) -> int:
    parser = _build_parser()
    args = parser.parse_args(argv)
    config = _config_from_args(args)
    try:
        if args.command == "up":
            start_pgvector(config)
            if args.write_env_file:
                write_env_file(config)
            if args.migrate:
                run_migrations(config)
            _print_success(config, wrote_env=args.write_env_file)
            return 0
        if args.command == "migrate":
            run_migrations(config)
            return 0
        if args.command == "test":
            run_external_migration_smoke(config)
            return 0
        if args.command == "down":
            run(["docker", "stop", config.container], check=False)
            return 0
        if args.command == "env":
            write_env_file(config)
            _print_env_help(config)
            return 0
    except CommandError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    parser.error("unknown command")
    return 2


def start_pgvector(config: PgvectorConfig) -> None:
    """Pull and start the local pgvector container."""
    _ensure_docker_available()
    if config.pull:
        run(["docker", "pull", config.image])
    run(["docker", "volume", "create", config.volume])
    if _container_exists(config.container):
        run(["docker", "start", config.container], check=False)
    else:
        run(
            [
                "docker",
                "run",
                "--detach",
                "--name",
                config.container,
                "--publish",
                f"{config.host}:{config.port}:5432",
                "--volume",
                f"{config.volume}:/var/lib/postgresql/data",
                "--env",
                f"POSTGRES_USER={config.user}",
                "--env",
                f"POSTGRES_PASSWORD={config.password}",
                "--env",
                f"POSTGRES_DB={config.database}",
                config.image,
            ]
        )
    _wait_for_pgvector(config)


def write_env_file(config: PgvectorConfig) -> None:
    """Write ignored local backend env wiring for the pgvector container."""
    content = "\n".join(
        [
            "# Local Docker pgvector wiring. This file is git-ignored.",
            "# Generated by: uv run python -m scripts.dev_pgvector env",
            f"MY_AGENTS_DATABASE_URL={config.database_url}",
            f"MY_AGENTS_TEST_DATABASE_URL={config.database_url}",
            "MY_AGENTS_AUTO_CREATE_TABLES=false",
            "MY_AGENTS_SESSION_COOKIE_SECURE=false",
            "MY_AGENTS_AUTH_EMAIL_MODE=local",
            "MY_AGENTS_AUTH_DEV_OUTBOX_ENABLED=true",
            "MY_AGENTS_CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000",
            "",
        ]
    )
    config.env_file.write_text(content, encoding="utf-8")


def run_migrations(config: PgvectorConfig) -> None:
    """Run Alembic migrations against the local pgvector database."""
    env = _backend_env(config)
    run([sys.executable, "-m", "alembic", "upgrade", "head"], env=env)


def run_external_migration_smoke(config: PgvectorConfig) -> None:
    """Run the gated Postgres migration smoke against the local pgvector database."""
    env = _backend_env(config)
    run([sys.executable, "-m", "pytest", "tests/test_migrations.py", "-q"], env=env)


def run(
    command: Sequence[str],
    *,
    env: dict[str, str] | None = None,
    check: bool = True,
) -> subprocess.CompletedProcess[str]:
    """Run a local command without printing secret-bearing env values."""
    result = subprocess.run(
        command,
        check=False,
        env=env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    if result.stdout:
        print(result.stdout.rstrip())
    if check and result.returncode != 0:
        raise CommandError(f"{command[0]} exited with status {result.returncode}")
    return result


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Start and wire a local Docker pgvector Postgres for this backend."
    )
    parser.add_argument(
        "command",
        choices=("up", "migrate", "test", "down", "env"),
        help=(
            "up: pull/start container; migrate: run Alembic; test: run gated migration smoke; "
            "down: stop container; env: write local env file only"
        ),
    )
    parser.add_argument(
        "--image", default=os.environ.get("MY_AGENTS_PGVECTOR_IMAGE", DEFAULT_IMAGE)
    )
    parser.add_argument(
        "--container",
        default=os.environ.get("MY_AGENTS_PGVECTOR_CONTAINER", DEFAULT_CONTAINER),
    )
    parser.add_argument(
        "--volume", default=os.environ.get("MY_AGENTS_PGVECTOR_VOLUME", DEFAULT_VOLUME)
    )
    parser.add_argument("--host", default=os.environ.get("MY_AGENTS_PGVECTOR_HOST", DEFAULT_HOST))
    parser.add_argument(
        "--port",
        type=int,
        default=int(os.environ.get("MY_AGENTS_PGVECTOR_PORT", str(DEFAULT_PORT))),
    )
    parser.add_argument("--user", default=os.environ.get("MY_AGENTS_PGVECTOR_USER", DEFAULT_USER))
    parser.add_argument(
        "--password",
        default=os.environ.get("MY_AGENTS_PGVECTOR_PASSWORD", DEFAULT_PASSWORD),
    )
    parser.add_argument(
        "--database",
        default=os.environ.get("MY_AGENTS_PGVECTOR_DATABASE", DEFAULT_DATABASE),
    )
    parser.add_argument(
        "--env-file",
        type=Path,
        default=Path(os.environ.get("MY_AGENTS_PGVECTOR_ENV_FILE", DEFAULT_ENV_FILE)),
    )
    parser.add_argument("--no-pull", action="store_true", help="Skip docker pull before start.")
    parser.add_argument(
        "--no-write-env-file",
        dest="write_env_file",
        action="store_false",
        help="Do not write the ignored .env.pgvector.local file during up.",
    )
    parser.add_argument(
        "--migrate",
        action="store_true",
        help="After up, run Alembic upgrade head against the local pgvector DB.",
    )
    parser.set_defaults(write_env_file=True)
    return parser


def _config_from_args(args: argparse.Namespace) -> PgvectorConfig:
    return PgvectorConfig(
        image=args.image,
        container=args.container,
        volume=args.volume,
        host=args.host,
        port=args.port,
        user=args.user,
        password=args.password,
        database=args.database,
        env_file=args.env_file,
        pull=not args.no_pull,
    )


def _ensure_docker_available() -> None:
    try:
        run(["docker", "version"], check=True)
    except FileNotFoundError as exc:
        raise CommandError("docker is not installed or not on PATH") from exc


def _container_exists(name: str) -> bool:
    result = run(
        ["docker", "ps", "--all", "--format", "{{.Names}}"],
        check=True,
    )
    return name in {line.strip() for line in result.stdout.splitlines()}


def _wait_for_pgvector(config: PgvectorConfig, *, timeout_seconds: int = 60) -> None:
    deadline = time.monotonic() + timeout_seconds
    while time.monotonic() < deadline:
        result = run(
            [
                "docker",
                "exec",
                config.container,
                "pg_isready",
                "-U",
                config.user,
                "-d",
                config.database,
            ],
            check=False,
        )
        if result.returncode == 0:
            return
        time.sleep(1)
    raise CommandError(f"pgvector container did not become ready within {timeout_seconds}s")


def _backend_env(config: PgvectorConfig) -> dict[str, str]:
    env = os.environ.copy()
    env["MY_AGENTS_DATABASE_URL"] = config.database_url
    env["MY_AGENTS_TEST_DATABASE_URL"] = config.database_url
    env["MY_AGENTS_AUTO_CREATE_TABLES"] = "false"
    return env


def _print_success(config: PgvectorConfig, *, wrote_env: bool) -> None:
    print(f"pgvector container ready: {config.container} ({config.image})")
    print(f"backend database URL: {config.masked_database_url}")
    if wrote_env:
        _print_env_help(config)
    print("next: re-ingest documents so Postgres embedding_vector values are populated")


def _print_env_help(config: PgvectorConfig) -> None:
    print(f"wrote ignored env file: {config.env_file}")
    print(f"load it with: set -a; source {config.env_file}; set +a")
    print("local signup will use the in-memory dev auth outbox, not SMTP")
    print("migrate with: uv run python -m scripts.dev_pgvector migrate")
    print("smoke with: uv run python -m scripts.dev_pgvector test")


if __name__ == "__main__":
    raise SystemExit(main())
